/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoseRouteImport } from './routes/rose'
import { Route as IndexRouteImport } from './routes/index'

const RoseRoute = RoseRouteImport.update({
  id: '/rose',
  path: '/rose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rose': typeof RoseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rose': typeof RoseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rose': typeof RoseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rose'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rose'
  id: '__root__' | '/' | '/rose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoseRoute: typeof RoseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rose': {
      id: '/rose'
      path: '/rose'
      fullPath: '/rose'
      preLoaderRoute: typeof RoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoseRoute: RoseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
